# Assign PR to Author
# https://github.com/samspills/assign-pr-to-author

name: Assign PR to Author
on: [pull_request]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: samspills/assign-pr-to-author@fa6bf795a8eeede8e72ddd284abbcc266fed4ba1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
